version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6
    container_name: timetable-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - timetable-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timetable-app
    ports:
      - "3001:3001"  # Backend API
      - "5173:5173"  # Frontend
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password@mongodb:27017/timetable_db?authSource=admin
      - JWT_SECRET=your_secure_jwt_secret_here
      - JWT_EXPIRE=30d
    networks:
      - timetable-network
    restart: unless-stopped

  # Seed Service (optional - uncomment to seed the database)
  # seed:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: timetable-seed
  #   command: ["node", "/app/backend/scripts/seedDatabase.js"]
  #   depends_on:
  #     app:
  #       condition: service_started
  #   environment:
  #     - NODE_ENV=production
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/timetable_db?authSource=admin
  #   networks:
  #     - timetable-network
  #   restart: on-failure

networks:
  timetable-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 