services:
  # Backend API service
  - type: web
    name: timetable-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
    healthCheckPath: /api/health
    
  # Frontend service definition removed. 
  # Please create and manage as a "Static Site" via Render Dashboard. 